name: frontend
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  markdown_widget: ^2.3.2+6
  riverpod: ^2.5.1
  toastification: ^2.3.0
  treemap:
    git:
      url: https://github.com/guchengxi1994/treemap.git
      ref: cb2ba3aa0a35e151d4ea03771966c3fad72d7786

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

