spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1:3307}/simplekb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1800000
      idle-timeout: 600000

  ai:
    openai:
      chat:
        options:
          model: ${CHAT_MODEL:Chat}
      embedding:
        options:
          model: ${EMBEDDING_MODEL:Embed}
        base-url: ${OPEN_AI_HOST:http://127.0.0.1:9997}
      api-key: ${SK:sk-X}
      base-url: ${OPEN_AI_HOST:http://127.0.0.1:9997}


swagger:
  # 是否开启swagger
  enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

server:
  servlet:
    context-path: /kb

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: isDeleted
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

qdrant:
  vector-size: ${QDRANT_VECTOR_SIZE:1024}
  host: ${QDRANT_HOST:127.0.0.1}
  port: 6334
  collection: simplekb

chunk:
  max-length: 500
  top-k: 20

filelist:
  page-size: 5

rerank:
  context-max-length: 5000
  score-threshold: 0.5
  model: ${RERANK_MODEL:Rerank}
  host: ${RERANK_HOST:http://127.0.0.1:9997/v1/rerank}